import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { ArrowLeft, Calendar, Mail, Globe } from "lucide-react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const LAST_UPDATED = "March 13, 2026";
const APP_NAME = "ApexCam";
const COMPANY_NAME = "ApexCam, operated by Apex View, registered in Israel";
const CONTACT_EMAIL = "legal@apex-view.org";
const WEBSITE = "https://apex-view.org/terms";

interface SectionProps {
  title: string;
  children: React.ReactNode;
}

function Section({ title, children }: SectionProps) {
  return (
    <div className="mb-8">
      <h2 className="text-xs font-bold tracking-widest uppercase text-primary mb-3 ml-1">
        {title}
      </h2>
      <div className="bg-card border border-border rounded-xl p-5 shadow-sm">
        {children}
      </div>
    </div>
  );
}

function BodyText({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <p className={`text-sm text-muted-foreground leading-relaxed ${className}`}>
      {children}
    </p>
  );
}

function Bullet({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex gap-2 mt-2 pl-1">
      <span className="text-primary text-sm leading-relaxed shrink-0">•</span>
      <span className="text-sm text-muted-foreground leading-relaxed">{children}</span>
    </div>
  );
}

export default function TermsPage() {
  const { t } = useTranslation();

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-24 pb-16">
        {/* Hero banner */}
        <div className="relative bg-gradient-to-br from-primary/20 via-primary/10 to-background py-12 mb-10 border-b border-border">
          <div className="container mx-auto px-6">
            <Link
              to="/"
              className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors mb-6"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to Home
            </Link>
            <h1 className="text-4xl font-bold text-foreground mb-3">Terms &amp; Conditions</h1>
            <div className="flex items-center gap-2 text-sm text-primary font-medium">
              <Calendar className="h-4 w-4" />
              <span>Last Updated: {LAST_UPDATED}</span>
            </div>
          </div>
        </div>

        <div className="container mx-auto px-6 max-w-3xl">
          {/* Intro */}
          <div className="mb-8 p-4 bg-primary/5 border border-primary/20 rounded-xl text-sm text-muted-foreground leading-relaxed">
            These Terms and Conditions govern your use of <strong className="text-foreground">{APP_NAME}</strong> ("the App"), operated by {COMPANY_NAME}. By using the App, you agree to these Terms.
          </div>

          <Section title="1. Acceptance of Terms">
            <BodyText>
              By downloading, installing, or using <strong className="text-foreground">{APP_NAME}</strong> ("the App"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree to these Terms, do not use the App.
            </BodyText>
            <BodyText className="mt-3">
              These Terms constitute a legally binding agreement between you ("User") and {COMPANY_NAME} ("we", "us", or "our"). We reserve the right to update these Terms at any time. Continued use of the App after changes constitutes acceptance of the revised Terms.
            </BodyText>
          </Section>

          <Section title="2. Description of Service">
            <BodyText>{APP_NAME} is a fleet camera management application that allows users to:</BodyText>
            <Bullet>View live camera streams from connected devices</Bullet>
            <Bullet>Access recorded video footage and playback history</Bullet>
            <Bullet>Monitor vehicle or device GPS location in real time</Bullet>
            <Bullet>Receive alerts and push notifications from connected cameras</Bullet>
            <Bullet>Manage device settings and configurations</Bullet>
            <Bullet>Capture media and view live streams</Bullet>
            <BodyText className="mt-3">
              The App connects to your own camera hardware and server infrastructure (CMSV6 or compatible). We do not own, operate, or control the camera devices or video content generated by them.
            </BodyText>
          </Section>

          <Section title="3. Account Access &amp; Security">
            <BodyText>
              Accounts for {APP_NAME} are provisioned directly by ApexCam and are not self-service. Access is granted to authorized personnel of customers with valid service agreements. You agree to:
            </BodyText>
            <Bullet>Maintain the confidentiality of your provisioned account credentials</Bullet>
            <Bullet>Notify us immediately of any unauthorized use or security breach</Bullet>
            <Bullet>Accept responsibility for all activities that occur under your account</Bullet>
            <BodyText className="mt-3">
              We reserve the right to suspend or terminate accounts that violate these Terms, applicable laws, or the terms of the underlying service agreement.
            </BodyText>
          </Section>

          <Section title="4. Acceptable Use">
            <BodyText>You agree to use the App only for lawful purposes. You must not:</BodyText>
            <Bullet>Use the App to surveil individuals without their knowledge or legal authorization</Bullet>
            <Bullet>Violate any applicable laws, including privacy and surveillance laws in your jurisdiction</Bullet>
            <Bullet>Attempt to reverse-engineer, decompile, or disassemble the App</Bullet>
            <Bullet>Use the App to transmit malicious code, spam, or harmful content</Bullet>
            <Bullet>Interfere with the App's servers, networks, or security features</Bullet>
            <Bullet>Use the App for commercial resale without our explicit written permission</Bullet>
            <BodyText className="mt-3">
              You are solely responsible for ensuring your use of the App complies with local surveillance, privacy, and data protection laws (including but not limited to GDPR, CCPA, and local equivalents).
            </BodyText>
            <BodyText className="mt-3">
              Users are solely responsible for ensuring that their use of surveillance devices complies with applicable privacy and surveillance laws in their jurisdiction.
            </BodyText>
          </Section>

          <Section title="5. Device Permissions">
            <BodyText>
              The App accesses your device's camera, microphone, location, and media library to provide its core functionality. Specifically:
            </BodyText>
            <Bullet><strong className="text-foreground">Camera &amp; Microphone:</strong> Used for live streaming and video capture.</Bullet>
            <Bullet><strong className="text-foreground">Location:</strong> Used to display GPS coordinates of tracked vehicles or devices. Background location is used only when tracking is explicitly active.</Bullet>
            <Bullet><strong className="text-foreground">Media Library:</strong> Used to save captured photos and video clips to your device.</Bullet>
            <Bullet><strong className="text-foreground">Push Notifications:</strong> Used to deliver real-time alerts from your cameras.</Bullet>
            <BodyText className="mt-3">
              All camera streams are transmitted between your devices and your own server infrastructure. We do not store, process, or access your camera footage.
            </BodyText>
          </Section>

          <Section title="6. Third-Party Services">
            <BodyText>
              The App integrates with the following third-party services, each governed by their own terms and privacy policies:
            </BodyText>
            <Bullet><strong className="text-foreground">Supabase</strong> — Authentication and database. (supabase.com/terms)</Bullet>
            <Bullet><strong className="text-foreground">Google Maps Platform</strong> — Map display and location services. (cloud.google.com/maps-platform/terms)</Bullet>
            <Bullet><strong className="text-foreground">Firebase (Google)</strong> — Push notification delivery. (firebase.google.com/terms)</Bullet>
            <BodyText className="mt-3">
              We are not responsible for the content, privacy practices, or terms of any third-party services.
            </BodyText>
          </Section>

          <Section title="7. Intellectual Property">
            <BodyText>
              All intellectual property rights in the App, including but not limited to software, design, trademarks, logos, and documentation, are owned by or licensed to {COMPANY_NAME}.
            </BodyText>
            <BodyText className="mt-3">
              You are granted a limited, non-exclusive, non-transferable, revocable license to use the App for personal or internal business purposes. You may not copy, modify, distribute, sell, or sublicense any part of the App.
            </BodyText>
            <BodyText className="mt-3">
              Video content captured through your connected devices remains your property. We claim no ownership over footage generated by your cameras.
            </BodyText>
          </Section>

          <Section title="8. Disclaimer of Warranties">
            <BodyText>
              THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES INCLUDING:
            </BodyText>
            <Bullet>Merchantability or fitness for a particular purpose</Bullet>
            <Bullet>Uninterrupted, error-free, or secure operation of the App</Bullet>
            <Bullet>Accuracy or reliability of any information in the App</Bullet>
            <Bullet>That defects will be corrected</Bullet>
            <BodyText className="mt-3">
              Camera connectivity and live streaming reliability depend on your network infrastructure, device hardware, and server setup. We are not responsible for connection failures or data loss.
            </BodyText>
          </Section>

          <Section title="9. Subscriptions &amp; Billing">
            <BodyText>
              Access to {APP_NAME} services is provided under separate agreements between ApexCam and its customers. The following terms apply to subscriptions and billing:
            </BodyText>
            <Bullet>The App itself does not offer in-app purchases, process payments, or collect billing information.</Bullet>
            <Bullet>Subscription fees are billed and managed outside of the App through direct contractual arrangements.</Bullet>
            <Bullet>All payment terms, renewals, and cancellations are governed by your specific service agreement with ApexCam.</Bullet>
            <Bullet>Failure to maintain a valid subscription may result in suspension of App access.</Bullet>
          </Section>

          <Section title="10. Force Majeure">
            <BodyText>
              ApexCam shall not be liable for any delay or failure to perform its obligations under these Terms, nor for any service interruptions, caused by Force Majeure events beyond our reasonable control, including but not limited to:
            </BodyText>
            <Bullet>War, hostilities, or acts of terrorism</Bullet>
            <Bullet>Cyberattacks, data breaches, or infrastructure failures</Bullet>
            <Bullet>Government restrictions, sanctions, or legal changes</Bullet>
            <Bullet>Natural disasters, pandemics, or labor strikes</Bullet>
            <Bullet>Telecommunications outages or internet service disruptions</Bullet>
          </Section>

          <Section title="11. Limitation of Liability">
            <BodyText>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, {COMPANY_NAME.toUpperCase()} SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
            </BodyText>
            <Bullet>YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE APP</Bullet>
            <Bullet>ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE</Bullet>
            <Bullet>ANY CONTENT OBTAINED FROM THE SERVICE</Bullet>
            <Bullet>UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT</Bullet>
            <BodyText className="mt-3">
              IN NO EVENT SHALL OUR AGGREGATE LIABILITY EXCEED THE GREATER OF ONE HUNDRED U.S. DOLLARS (U.S. $100.00) OR THE AMOUNT YOU PAID US, IF ANY, IN THE PAST TWELVE MONTHS FOR THE SERVICES GIVING RISE TO THE CLAIM.
            </BodyText>
          </Section>

          <Section title="12. Privacy Policy">
            <BodyText>
              Your use of the App is also governed by our{" "}
              <Link to="/privacy" className="text-primary hover:underline font-medium">
                Privacy Policy
              </Link>
              , which is incorporated into these Terms by reference. Please review our Privacy Policy to understand our data practices.
            </BodyText>
          </Section>

          <Section title="13. Termination">
            <BodyText>
              We reserve the right to suspend or terminate your access to the App at any time, with or without notice, for reasons including but not limited to:
            </BodyText>
            <Bullet>Misuse of the App or violation of these Terms</Bullet>
            <Bullet>Non-payment of subscription fees by your organization</Bullet>
            <Bullet>Legal or regulatory violations</Bullet>
            <Bullet>Technical issues or security concerns</Bullet>
            <BodyText className="mt-3">
              Upon termination, your right to use the App immediately ceases.
            </BodyText>
          </Section>

          <Section title="14. Governing Law &amp; Jurisdiction">
            <BodyText>
              These Terms and any dispute or claim arising out of or in connection with them shall be governed by and construed in accordance with the laws of the{" "}
              <strong className="text-foreground">State of Israel</strong>. ApexCam is operated by Apex View, registered in Israel.
            </BodyText>
            <BodyText className="mt-3">
              Any dispute, controversy, or claim arising out of or relating to these Terms, including the validity, invalidity, breach, or termination thereof, shall be settled by{" "}
              <strong className="text-foreground">arbitration in Israel</strong>.
            </BodyText>
            <BodyText className="mt-3">
              For any matters not subject to arbitration, you irrevocably submit to the exclusive jurisdiction of the competent courts in{" "}
              <strong className="text-foreground">Tel Aviv, Israel</strong>.
            </BodyText>
          </Section>

          <Section title="15. Changes to Terms">
            <BodyText>
              We reserve the right to modify these Terms at any time. When we make material changes, we will notify you through the App or by email. Your continued use of the App after the effective date of changes constitutes your acceptance of the revised Terms.
            </BodyText>
          </Section>

          <Section title="16. Contact Us">
            <BodyText>If you have any questions about these Terms and Conditions, please contact us:</BodyText>
            <div className="mt-4 p-4 bg-primary/5 border-l-4 border-primary rounded-r-lg space-y-2">
              <div className="flex items-center gap-2 text-sm">
                <Mail className="h-4 w-4 text-primary shrink-0" />
                <span className="font-semibold text-foreground">Email:</span>
                <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary hover:underline">{CONTACT_EMAIL}</a>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <Globe className="h-4 w-4 text-primary shrink-0" />
                <span className="font-semibold text-foreground">Website:</span>
                <a href={WEBSITE} target="_blank" rel="noreferrer" className="text-primary hover:underline">{WEBSITE}</a>
              </div>
              <div className="text-sm">
                <span className="font-semibold text-foreground">App:</span>{" "}
                <span className="text-muted-foreground">{APP_NAME}</span>
              </div>
            </div>
          </Section>

          <p className="text-center text-xs text-muted-foreground/50 mt-8">
            © {new Date().getFullYear()} {COMPANY_NAME}. All rights reserved.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
