// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlvoebgwzsoghycumjuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsdm9lYmd3enNvZ2h5Y3VtanVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzODk0MjMsImV4cCI6MjA3NDk2NTQyM30.KjNOjUomCKsb2n_y2zBI7qGIlG9RHEltSQKPQ3PpkqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});